[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pypnm"
version = "1.0.0"
description = "DOCSIS 3.1/4.0 Proactive Network Maintenance Toolkit"
readme = "README.md"
requires-python = ">=3.10"

# Core runtime dependencies
dependencies = [
  "fastapi>=0.95.0",
  "uvicorn[standard]>=0.22.0",
  "numpy>=1.25.0",
  "pysnmp>=7.1.20",
  "python-dotenv>=1.0.0"
]

# Optional groups of dependencies
[project.optional-dependencies]
dev = [
  "pytest>=7.4.0",
  "pytest-cov",          # coverage reporting
  "black",               # code formatting
  "mypy",                # static typing checks
]

[project.urls]
"Homepage" = "https://github.com/mgarcia01752/PyPNM"
"Repository" = "https://github.com/mgarcia01752/PyPNM"
"Bug Tracker" = "https://github.com/mgarcia01752/PyPNM/issues"

[project.authors]
name = "Maurice Garcia"
email = "mgarcia01752@outlook.com"
